---
# infoblox/playbooks/add/nios_range.yml

# This playbook manages Infoblox NIOS network range objects.

- name: Read Range data from JSON file
  ansible.builtin.set_fact:
    nios_range_desired: "{{ lookup('file', 'add/prod_changes/{{ grid_host }}/network_range.json') | from_json }}"

- name: Ensure Ranges are present
  infoblox.nios_modules.nios_range:
    provider: "{{ clean_provider }}"
    network: "{{ item.network }}"
    start_addr: "{{ item.start_addr }}"
    end_addr: "{{ item.end_addr }}"
    comment: "{{ item.comment | default(omit) }}"
    disable: "{{ item.disable | default(omit) }}"
    extattrs: "{{ item.extattrs | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    network_view: "{{ item.network_view | default(omit) }}"
    options: "{{ item.options | default(omit) }}"
    server_association_type: "{{ item.server_association_type | default(omit) }}"
    failover_association: "{{ item.failover_association | default(omit) }}"
    member: "{{ item.member.name | default(omit) }}" # Extract member name
    ms_server: "{{ item.ms_server | default(omit) }}"
    state: present
  loop: "{{ nios_range_desired }}"
  register: add_result
  ignore_errors: true

- name: Display Add Range results
  ansible.builtin.debug:
    var: add_result
  when: add_result is defined and add_result.changed

- name: Playbook completed
  ansible.builtin.debug:
    msg: "Playbook completed: Range objects process completed."
