---
# infoblox/playbooks/add/nios_aaaa_record.yml

# This playbook manages Infoblox NIOS AAAA records.

- name: Read AAAA record data from JSON file using slurp
  ansible.builtin.slurp:
    path: "add/prod_changes/{{ grid_host }}/aaaa_record.json"
  register: slurped_aaaa_record

- name: Set fact from slurped JSON data
  ansible.builtin.set_fact:
    nios_aaaa_record_desired: "{{ slurped_aaaa_record['content'] | b64decode | from_json }}"

- name: Debug nios_aaaa_record_desired
  ansible.builtin.debug:
    var: nios_aaaa_record_desired

- name: Ensure AAAA records are present
  infoblox.nios_modules.nios_aaaa_record:
    provider: "{{ clean_provider }}"
    name: "{{ item.name }}"
    ipv6addr: "{{ item.ipv6addr }}"
    comment: "{{ item.comment | default(omit) }}"
    extattrs: "{{ item.extattrs | default(omit) }}"
    view: "{{ item.view }}"
    state: present
  loop: "{{ nios_aaaa_record_desired }}"
  register: add_result
  ignore_errors: false

- name: Display Add AAAA record errors
  ansible.builtin.debug:
    var: item
  loop: "{{ add_result.results }}"
  when: item.failed

- name: Playbook completed
  ansible.builtin.debug:
    msg: "Playbook completed: AAAA record objects process completed."
