---
# infoblox/playbooks/add/nios_a_record.yml

# This playbook manages infoblox NIOS A records.

- name: Set fact from JSON file data
  ansible.builtin.set_fact:
    nios_a_record_desired: "{{ lookup('file', json_file) | from_json }}"
    operation_type: "{{ operation | default('add') }}"

- name: Debug nios_a_record_desired
  ansible.builtin.debug:
    var: nios_a_record_desired

- name: Ensure A records are present
  infoblox.nios_modules.nios_a_record:
    provider: "{{ clean_provider }}"
    name: "{{ item.name }}"
    ipv4addr: "{{ item.ipv4addr }}"
    comment: "{{ item.comment | default('') }}"
    extattrs: "{{ item.extattrs | default({}) }}"
    view: "{{ item.view }}"
    state: "{{ 'present' if operation_type == 'add' else 'absent' }}"
  loop: "{{ nios_a_record_desired }}"
  register: add_result
  ignore_errors: false

- name: Display Add A record errors
  ansible.builtin.debug:
    var: item
  loop: "{{ add_result.results }}"
  when: item.failed

- name: Playbook completed
  ansible.builtin.debug:
    msg: "Playbook completed: A record objects process completed."
