---
# infoblox/playbooks/nios_host_record.yml

# This playbook manages infobox NIOS host records.


- name: Manage Infoblox HOST Records
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Set fact from JSON file data
      ansible.builtin.set_fact:
        nios_host_record_desired: "{{ lookup('file', json_file) | from_json }}"
        operation_type: "{{ operation | default('add') }}"

    - name: Debug nios_host_record_desired
      debug:
        var: nios_host_record_desired

    - name: Ensure host records are present
      infoblox.nios_modules.nios_host_record:
        provider: "{{ clean_provider }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment | default(omit) }}"
        configure_for_dns: "{{ item.configure_for_dns | default(omit) }}"
        extattrs: "{{ item.extattrs | default(omit) }}"
        view: "{{ item.view }}"
        ipv4addrs: "{{ item.ipv4addrs | default(omit) }}"
        ipv6addrs: "{{ item.ipv6addrs | default(omit) }}"
        state: "{{ 'present' if operation_type == 'add' else 'absent' }}"
      loop: "{{ nios_host_record_desired }}"
      register: add_result
      ignore_errors: false

    - name: Display Add host record errors
      debug:
        var: item
      loop: "{{ add_result.results }}"
      when: item.failed

    - name: Playbook completed
      debug:
        msg: "Playbook completed: Host record objects process completed."
