---
# infoblox/playbooks/add/nios_network.yml

- name: Set fact from JSON file data
  ansible.builtin.set_fact:
    nios_network_desired: "{{ lookup('file', json_file) | from_json }}"
    operation_type: "{{ operation | default('add') }}"

- name: Define Supported DHCP Options
  ansible.builtin.set_fact:
    supported_dhcp_options:
      - subnet-mask
      - time-offset
      - routers
      - time-servers
      - name-servers
      - domain-name-servers
      - log-servers
      - cookie-servers
      - lpr-servers
      - impress-servers
      - resource-location-servers
      - boot-size
      - merit-dump
      - domain-name
      - swap-server
      - root-path
      - extensions-path
      - ip-forwarding
      - non-local-source-routing
      - policy-filter
      - max-dgram-reassembly
      - default-ip-ttl
      - path-mtu-aging-timeout
      - path-mtu-plateau-table
      - interface-mtu
      - all-subnets-local
      - broadcast-address
      - perform-mask-discovery
      - mask-supplier
      - router-discovery
      - router-solicitation-address
      - static-routes
      - trailer-encapsulation
      - arp-cache-timeout
      - ieee802-3-encapsulation
      - default-tcp-ttl
      - tcp-keepalive-interval
      - tcp-keepalive-garbage
      - nis-domain
      - nis-servers
      - ntp-servers
      - vendor-encapsulated-options
      - netbios-name-servers
      - netbios-dd-server
      - netbios-node-type
      - netbios-scope
      - font-servers
      - x-display-manager
      - dhcp-option-overload
      - dhcp-server-identifier
      - dhcp-message
      - dhcp-max-message-size
      - vendor-class-identifier
      - nwip-domain-name
      - nisplus-domain-name
      - nisplus-severs
      - tftp-server-name
      - boot-file-name
      - mobile-ip-home-agent
      - smtp-server
      - pop-server
      - nntp-server
      - www.-server
      - finger-server
      - irc-server
      - streettalk-server
      - streettalk-directory-assistance-server
      - user-class
      - slp-directory-agent
      - slp-service-scope
      - nds-server
      - nds-tree-name
      - nds-context
      - bcms-controller-names
      - bcms-controller-address
      - client-system
      - client-ndi
      - uuid-guid
      - uap-servers
      - geoconf-civic
      - pcode
      - tcode
      - netinfo-server-address
      - netinfo-server-tag
      - v4-captive-portal+
      - auto-config
      - name-server-search
      - subnet-selection
      - domain-search
      - vivco-suboptions
      - vivso-suboptions
      - pana-agent
      - v4-lost
      - capwap-ac-v4
      - sip-ua-cs-domains
      - rdnss-selection
      - v4-portparams
      - v4-captive-portal-old+
      - option-6rd
      - v4-access-domain
      - dhcp-lease-time

- name: Ensure network objects are present
  infoblox.nios_modules.nios_network:
    provider: "{{ clean_provider }}"
    network: "{{ item.network }}"
    network_view: "{{ item.network_view | default('default') }}"
    comment: "{{ item.comment | default(omit) }}"
    options: "{{ item.options | default(omit) }}"
    extattrs: "{{ item.extattrs | default(omit) }}"
    members: "{{ item.members | default(omit) }}"
    state: present
  loop: "{{ nios_network_desired }}"
  register: add_result
  ignore_errors: true

# Display Add network errors
- name: Display Add network errors
  ansible.builtin.debug:
    var: add_result
  when: add_result is defined and 'failed' in add_result and add_result.failed

# Playbook completed
- name: Playbook completed
  ansible.builtin.debug:
    msg: "Playbook completed: Network objects process completed."
